### ISSUE TITLE
Incompatible with click >= 8.1

### ISSUE THREAD

**Issue by b00bl1k** [codito/habito#30]
Hi, version 1.0.0 in AUR is incompatible with click 8.1.3 which is in archlinux package repository, because the function `get_terminal_size` has been deleted, see https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-0

```
Traceback (most recent call last):
  File "/usr/bin/habito", line 33, in <module>
    sys.exit(load_entry_point('habito==1.0.0', 'console_scripts', 'habito')())
  File "/usr/bin/habito", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/habito/habito.py", line 15, in <module>
    TERMINAL_WIDTH, TERMINAL_HEIGHT = click.get_terminal_size()
AttributeError: module 'click' has no attribute 'get_terminal_size'
```

**Comment by codito** [comment]
@b00bl1k thank you for reporting this. Fixed in v1.1. Updated the AUR package too.

Wish you a great new year :)
